CREATE TABLE `wp_usermeta` (  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `meta_value` longtext COLLATE utf8mb4_unicode_520_ci,  PRIMARY KEY (`umeta_id`),  KEY `user_id` (`user_id`),  KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_usermeta` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_usermeta` VALUES('1', '1', 'nickname', 'errobi');
INSERT INTO `wp_usermeta` VALUES('2', '1', 'first_name', '');
INSERT INTO `wp_usermeta` VALUES('3', '1', 'last_name', '');
INSERT INTO `wp_usermeta` VALUES('4', '1', 'description', '');
INSERT INTO `wp_usermeta` VALUES('5', '1', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('6', '1', 'syntax_highlighting', 'true');
INSERT INTO `wp_usermeta` VALUES('7', '1', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('8', '1', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('9', '1', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('10', '1', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('11', '1', 'locale', '');
INSERT INTO `wp_usermeta` VALUES('12', '1', 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('13', '1', 'wp_user_level', '10');
INSERT INTO `wp_usermeta` VALUES('14', '1', 'dismissed_wp_pointers', '');
INSERT INTO `wp_usermeta` VALUES('15', '1', 'show_welcome_panel', '1');
INSERT INTO `wp_usermeta` VALUES('16', '1', 'session_tokens', 'a:1:{s:64:\"f0af0ca3bd56916019580ecfc3a976b6dc11c543a850d6e6d9b3c0390a0be8ad\";a:4:{s:10:\"expiration\";i:1571603874;s:2:\"ip\";s:9:\"127.0.0.1\";s:2:\"ua\";s:114:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\";s:5:\"login\";i:1570394274;}}');
INSERT INTO `wp_usermeta` VALUES('17', '1', 'wp_dashboard_quick_press_last_post_id', '4');
INSERT INTO `wp_usermeta` VALUES('18', '1', 'community-events-location', 'a:1:{s:2:\"ip\";s:9:\"127.0.0.0\";}');
/*!40000 ALTER TABLE `wp_usermeta` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
